// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wbhu7Nu9z-gNGP3dlSp9EuO2Hn23hGw',
    appId: '1:186410697349:web:b13e4aaa938aa3228cdfec',
    messagingSenderId: '186410697349',
    projectId: 'my-authentication-204',
    authDomain: 'my-authentication-204.firebaseapp.com',
    storageBucket: 'my-authentication-204.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZCtPqQvuHK_XCLpmAYCJrkYgcPuQfA0',
    appId: '1:186410697349:android:300452619b62ccec8cdfec',
    messagingSenderId: '186410697349',
    projectId: 'my-authentication-204',
    storageBucket: 'my-authentication-204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3K2xjjxsdpIy7cm4UthsCInTRJw8JuZs',
    appId: '1:186410697349:ios:3aba2f2458e67d028cdfec',
    messagingSenderId: '186410697349',
    projectId: 'my-authentication-204',
    storageBucket: 'my-authentication-204.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3K2xjjxsdpIy7cm4UthsCInTRJw8JuZs',
    appId: '1:186410697349:ios:3aba2f2458e67d028cdfec',
    messagingSenderId: '186410697349',
    projectId: 'my-authentication-204',
    storageBucket: 'my-authentication-204.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4wbhu7Nu9z-gNGP3dlSp9EuO2Hn23hGw',
    appId: '1:186410697349:web:f88820aee19d825d8cdfec',
    messagingSenderId: '186410697349',
    projectId: 'my-authentication-204',
    authDomain: 'my-authentication-204.firebaseapp.com',
    storageBucket: 'my-authentication-204.appspot.com',
  );
}
